### ISSUE TITLE
UI Improvements Necessary

### ISSUE THREAD

**Issue by renatonascalves** [danielbachhuber/simpletts#17]
While testing, I see some UI issues that can allow the user to be confused.

1 - If you add one audio. Then you try to add another one, there seems to be a nonce problem. The plugin doesn't recognize the nonce and throws to the user an error. Even though it saves the audio in the media library.

2 - After clicking in the second Convert Text to Speech button, it should have a loading icon or a ui change is necessary to hint to the user that is working or not. Right now the user gets confused and don't know if it really worked. There is a subtle change in the button color but it doesn't tell if an error occurred. Forcing me to retry again. Then if I try again it shows the default error: "Sorry, you don't have permission to do this.".

As of right now, the plugin is working ok only if you try to convert the whole text once. If you try to create multiple audios in the same post, one has to constantly reload the page to refresh the nonce so that it can work as it should.

**Comment by renatonascalves** [comment]
@danielbachhuber I think the issue is in this line: https://github.com/danielbachhuber/simpletts/blob/master/assets/js/editor.js#L118

Testing here I changed `options.state` to `workflow.state` and it fixed the issue of adding another audio without reloading the page.

**Comment by danielbachhuber** [comment]
Thanks for the report @renatonascalves. I'll dive into this when I have a moment.

**Comment by renatonascalves** [comment]
Upon testing it seems there is still problem when adding more than two audios in the same page without reloading it.

The problem lies in the WordPress media editor code part. It is not updating the screen with the 'current' selection. The audio is uploaded to the media library though.

![screenshot_1](https://user-images.githubusercontent.com/19148962/29487463-b24e358c-84cf-11e7-859c-650e1cc5534f.png)
