### ISSUE TITLE
Clean text before conversion to avoid backslash output in the audio

### ISSUE THREAD

**Issue by renatonascalves** [danielbachhuber/simpletts#20]
Another problem while testing here. The audio is outputting/"adding" a backslash in the audio when the content has an apostrophe.

See this example: She didn't finish her homework.
Test Audio: https://inglesnarede.com.br/wp-content/uploads/2017/08/almanac-6984-2571b95.mp3

So the content needs sanitization/cleaning here: https://github.com/danielbachhuber/simpletts/blob/master/src/Admin_Ajax.php#L39

before being converted to audio.

**Comment by danielbachhuber** [comment]
Good catch! Fixed in #22
